version: '3.1'
services:
  app:
    container_name: agosh-app
    image: agosh-app
    build: ./
    ports:
      - "9090:9090"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=agosh_app_db